name: Check Cached Release Cycle

on:
  workflow_dispatch:
  schedule:
    # EOLs are currently scheduled for 20xx-10-01
    - cron: "0 14 2 1,4,7,10 *"

jobs:
  bump-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.x"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Bump Cache
      id: bump
      env:
        PUBLIC_PAT: ${{ secrets.PUBLIC_PAT }}
      run: |
        uv sync --no-dev --extra gha
        uv run ./pre_commit_python_eol/bump_cache.py
        {
          echo 'RES<<EOF'
          git diff ./pre_commit_python_eol/cached_release_cycle.json
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Set Date
      id: date
      run:
        echo "today=$(date +"%Y-%m-%d")" >> "$GITHUB_OUTPUT"

    - name: Create Pull Request If Bumped
      uses: peter-evans/create-pull-request@v7
      with:
        branch: "bump-cache"
        title: "chore: update release cycle cache (${{ steps.date.outputs.today }})"
        commit-message: "chore: update release cycle cache (${{ steps.date.outputs.today }})"
